apiVersion: v1
kind: Namespace
metadata:
  name: teamorange

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: orangecronjob
  namespace: teamorange
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: orangecronjob
            image: busybox
            args:
              - /bin/sh
              - -c
              - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure